version: "3.9"

services:
  tests_app:
    build: .
    container_name: tests_app
    ports:
      - "8080:8080"
#    volumes:
#      - ./static:/app/static
    depends_on:
      - database
  database:
    image: postgres:15
    ports:
      - "6000:5432" # localhost:6000 - migrate, VSC extension
    env_file:
      - .env
    volumes:
      - ../postgres:/var/lib/postgresql/data
